.\" Man page for ukui-system-monitor
.TH UKUISYSTEMMONITOR 1 "17 December 2019" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
ukui-system-monitor \- The tool for the UKUI Desktop Environment
.SH "SYNOPSIS"
.B ukui-system-monitor
.SH "DESCRIPTION"
The \fBukui-system-monitor\fR program is a part of the ukui-system-monitor, it provides users with graphical interface tools.
.PP
This manual page documents the \fBukui-system-monitor\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/ukui/ukui-system-monitor/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
tangguang <tangguang@tj.kylinos.cn> (2020)
.SH "SEE ALSO"
